User Authentication/app/models.py
from app import db
from flask_jwt_extended import JWTManager
from datetime import datetime

class User(db.Model):
    __tablename__ = "user"

    id = db.Column(db.String(20), primary_key=True)
    firstname = db.Column(db.String(100), nullable=False)
    lastname = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    school = db.Column(db.String(100), nullable=False)
    address = db.Column(db.String(100), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')

    def __repr__(self):
        return f"User('{self.firstname}', '{self.email}', '{self.image_file}')"

class Post(db.Model):
    __tablename__ = "post"

    id = db.Column(db.String(20), primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime)
    content = db.Column(db.Text, nullable=False)
    secret = db.Column(db.Boolean, nullable=False, default=False)
    secret_password = db.Column(db.String(60), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

User Authentication/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_jwt_extended import JWTManager
from flask_bcrypt import Bcrypt
from config import Config

db = SQLAlchemy()
jwt = JWTManager()
bcrypt = Bcrypt()

def create_app():
    app = Flask(__name__)
    # 환경변수 세팅
    app.config.from_object(Config)

    db.init_app(app) 
    jwt.init_app(app)
    bcrypt.init_app(app)

    from app.models import User

    @jwt.user_lookup_loader
    def load_user_callback(_jwt_header, jwt_data):
        identity = jwt_data["sub"]
        return User.query.get(int(identity))
    
    from app.routes import main
    app.register_blueprint(main)

    return app

User Authentication/app/auth.py
from flask_jwt_extended import get_jwt_identity
from app.models import User

def is_login(token, firstname, logged_in):
    if token:
        try:
            identity = get_jwt_identity()  # 사용자 ID를 가져옵니다.
            user = User.query.get(identity)  # 사용자 정보를 데이터베이스에서 조회합니다.
            if user:
                logged_in = True
                firstname = user.firstname  # 사용자 이름을 가져옵니다.
        except Exception:
            logged_in = False
    return 

User Authentication/app/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_jwt_extended import create_access_token, jwt_required, get_jwt_identity
from app import db, bcrypt
from app.models import User, Post

main = Blueprint('main', __name__)

@main.route("/")
def noticeboard():
    posts = Post.query.all()
    token = request.cookies.get('access_token')
    logged_in = False
    firstname = None
    if token:
        try:
            identity = get_jwt_identity()  # 사용자 ID를 가져옵니다.
            user = User.query.get(identity)  # 사용자 정보를 데이터베이스에서 조회합니다.
            if user:
                logged_in = True
                firstname = user.firstname  # 사용자 이름을 가져옵니다.
        except Exception:
            logged_in = False
    return render_template('noticeboard.html', posts=posts, logged_in=logged_in, firstname=firstname)



@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        id = request.form.get('id')
        password = request.form.get('password')
        user = User.query.filter_by(id=id).first()

        if user and bcrypt.check_password_hash(user.password, password):
            access_token = create_access_token(identity=user.id)
            response = redirect(url_for('main.noticeboard'))
            response.set_cookie('access_token', access_token, httponly=True)
            flash('Logged in successfully!', 'success')
            return response
        else:
            flash('Login failed. Check your ID and Password.', 'danger')
    return render_template('login.html')

@main.route('/logout')
@jwt_required(optional=False)
def logout():
    response = redirect(url_for('main.noticeboard'))
    response.delete_cookie('access_token')
    flash('You have been logged out.', 'info')
    return response

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        id = request.form.get('id')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        password = request.form.get('password')
        hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
        email = request.form.get('email')
        school = request.form.get('school')
        address = request.form.get('address')

        user = User(id=id, firstname=firstname, lastname=lastname, password=hashed_password, email=email, school=school, address=address)
        db.session.add(user)
        db.session.commit()
        flash('Registered successfully!', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html')

@main.route('/post_create', methods=['GET', 'POST'])
@jwt_required()
def post_create():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        secret = request.form.get('secret')
        secret_password = request.form.get('secret_password')
        user_id = get_jwt_identity()
        post = Post(title=title, content=content, secret=secret, secret_password=secret_password, user_id=user_id)
        db.session.add(post)
        db.session.commit()
        flash('Post created successfully!', 'success')
        return redirect(url_for('main.noticeboard'))
    return render_template('post_create.html')

@main.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.is_secret:  # 비밀글인지 확인합니다.
        if request.method == 'POST':
            input_password = request.form.get('password')

            # 비밀글의 비밀번호를 확인합니다.
            if bcrypt.check_password_hash(post.password, input_password):
                session[f'post_{post_id}_access'] = True  # 세션에 접근 권한을 저장합니다.
                return render_template('post.html', post=post)
            else:
                flash('Incorrect password. Please try again.', 'danger')

    # 비밀글이 아니거나 비밀번호가 올바른 경우 게시글을 표시합니다.
    return render_template('post.html', post=post)

@main.route('/search', methods=['GET'])
def search():
    search_type = request.args.get('type')
    keyword = request.args.get('keyword')

    if search_type == 'title':
        posts = Post.query.filter(Post.title.like(f'%{keyword}%')).all()
    elif search_type == 'content':
        posts = Post.query.filter(Post.content.like(f'%{keyword}%')).all()
    else:
        posts = []

    return render_template('post_search.html', posts=posts, keyword=keyword)

User Authentication/app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form method="POST" action="{{ url_for('main.login') }}">
        <table>
            <tr>
                <td><label for="id">ID</label></td>
                <td><input type="text" name="id" required></td>
            </tr>
            <tr>
                <td><label for="password">Password</label></td>
                <td><input type="password" name="password" required></td>
            </tr>
            <tr>
                <td colspan="2"><button type="submit">Login</button></td>
            </tr>
            <tr>
                <td colspan="2"><br><a href="{{ url_for('main.noticeboard') }}">Go to home</a></td>
            </tr>
        </table>
    </form>
</body>
</html>

User Authentication/app/templates/noticeboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Notice Board</title>
</head>
<body>
    <h1>Notice Board</h1>
    {% if logged_in %}
        <p>Welcome {{ firstname }}!</p>
        <a href="{{ url_for('main.logout') }}">Logout</a>
    {% else %}
        <a href="{{ url_for('main.login') }}">Login</a>
        <a href="{{ url_for('main.register') }}">Register</a>
    {% endif %}
    <br>
    <br>
    <a href="{{ url_for('main.post_create') }}">New Post</a>

    <form action="{{ url_for('main.search') }}" method="GET">
        <select name="type">
            <option value="title">Title</option>
            <option value="content">Context</option>
        </select>
        <input type="text" name="keyword" placeholder="검색어">
        <button type="submit">Search</button>
    </form>
    
    <ul>
        {% for post in posts %}
            <li><a href="{{ url_for('main.post', post_id=post.id) }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

User Authentication/app/templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
    <h1>POST</h1>
    {{}}

    <p>{{ post.title }}</p>
    <p>{{ post.content }}</p>
    {% if post.secret %}
        <p>This post is secret. Please enter the password to view the content.</p>
    {% endif %}
    {% if current_user == post.author %}
        <a href="{{ url_for('main.update_post', post_id=post.id) }}">Edit</a>
        <form method="POST" action="{{ url_for('main.delete_post', post_id=post.id) }}">
            <button type="submit">Delete</button>
        </form>
    {% endif %}
</body>
</html>

User Authentication/app/templates/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create New Post</title>
</head>
<body>
    <h1>Create New Post</h1>
    <form method="POST" action="{{ url_for('main.post_create') }}">
        <table>
            <tr>
                <td><label for="title">Title</label></td>
                <td><input type="text" name="title" required></td>
            </tr>
            <tr>
                <td><label for="content">Content</label></td>
                <td><textarea name="content" required></textarea></td>
            </tr>
            <tr>
                <td><label for="secret">Secret Post</label></td>
                <td><input type="checkbox" name="secret"></td>
            </tr>
            <tr>
                <td><label for="secret_password">Secret Post Password</label></td>
                <td><input type="password" name="secret_password"></td>
            </tr>
            <tr>
                <td colspan="2"><br><button type="submit">Create Post</button></td>
            </tr>
            <tr>
                <td colspan="2"><br><a href="{{ url_for('main.noticeboard') }}">Go to home</a></td>
            </tr>
        </table>
    </form>
</body>
</html>

User Authentication/app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form method="POST" action="{{ url_for('main.register') }}">
        <table>
            <tr>
                <td><label for="id">ID</label></td>
                <td><input type="text" name="id" required></td>
            </tr>
            <tr>
                <td><label for="firstname">First Name</label></td>
                <td><input type="text" name="firstname" required></td>
            </tr>
            <tr>
                <td><label for="lastname">Last Name</label></td>
                <td><input type="text" name="lastname" required></td>
            </tr>
            <tr>
                <td><label for="password">Password</label></td>
                <td><input type="password" name="password" required></td>
            </tr>
            <tr>
                <td><label for="email">Email</label></td>
                <td><input type="email" name="email" required></td>
            </tr>
            <tr>
                <td><label for="school">School</label></td>
                <td><input type="text" name="school" required></td>
            </tr>
            <tr>
                <td><label for="address">Address</label></td>
                <td><input type="text" name="address" required></td>
            </tr>
            <tr>
                <td colspan="2"><button type="submit">Register</button></td>
            </tr>
            <tr>
                <td colspan="2"><br><a href="{{ url_for('main.noticeboard') }}">Go to home</a></td>
            </tr>
        </table>        
    </form>
</body>
</html>